memo_project/urls.py
from django.contrib import admin
from django.urls import include, path
from memos import views

urlpatterns = [
    path('', views.redirect_view),
    path('memos/', include('memos.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
]

memos/urls.py
from django.urls import path

from . import views

app_name = 'memos'
urlpatterns = [
    # ex. /memos/
    path('', views.memo_list_view, name='memo-list'),
    # ex. /memos/create/
    path('create/', views.memo_create_view, name='memo-create'),
    # ex. /memos/{memo_id}/edit
    path('<int:memo_id>/edit/', views.memo_edit_view, name='memo-edit'),
    # ex. /memos/{memo_id}/delete/
    path('<int:memo_id>/delete/', views.memo_delete_view, name='memo-delete'),
]

memos/models.py
from django.db import models
from django.utils import timezone


class Memo(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=300)
    created_at = models.DateTimeField(default=timezone.now)

memos/forms.py
from django import forms


class MemoForm(forms.Form):
    title = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    content = forms.CharField(
        max_length=300,
        widget=forms.Textarea(attrs={'class': 'form-control'})
    )
    created_at = forms.DateTimeField(
        widget=forms.DateTimeInput(
            attrs={'class': 'form-control mb-2'},
            format="%Y-%m-%d %H:%M"
        )
    )

memos/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.utils import timezone


from .models import Memo
from .forms import MemoForm


def redirect_view(request):
    return redirect(reverse("memos:memo-list"))


def memo_list_view(request):
    memo_list = Memo.objects.all()
    context = {"memo_list": memo_list}
    return render(request, "memos/memo_list.html", context)


def memo_create_view(request):
    if request.method == "POST":
        form = MemoForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            created_at = form.cleaned_data["created_at"]
            memo = Memo(title=title, content=content, created_at=created_at)
            memo.save()
            return HttpResponseRedirect(reverse("memos:memo-list"))
        else:
            return render(request, "memos/memo_form.html", {
                "form": form, "error_message": "正しい値を入力してください"
            })
    else:
        form = MemoForm(initial={"created_at": timezone.now()})
        return render(request, "memos/memo_form.html", {"form": form})


def memo_edit_view(request, memo_id):
    if request.method == "POST":
        form = MemoForm(request.POST)
        memo = get_object_or_404(Memo, pk=memo_id)
        if form.is_valid():
            memo.title = form.cleaned_data["title"]
            memo.content = form.cleaned_data["content"]
            memo.created_at = form.cleaned_data["created_at"]
            memo.save()
            return HttpResponseRedirect(reverse("memos:memo-list"))
        else:
            return render(
                request,
                "memos/memo_form.html",
                {"memo": memo, "error_message": "正しい値を入力してください"},
            )
    else:
        memo = get_object_or_404(Memo, pk=memo_id)
        initial_data = {
            'title': memo.title,
            'content': memo.content,
            'created_at': memo.created_at
        }
        form = MemoForm(initial=initial_data)
        context = {"memo": memo, "form": form}
        return render(request, "memos/memo_form.html", context)


def memo_delete_view(request, memo_id):
    memo = get_object_or_404(Memo, pk=memo_id)
    if request.method == "POST":
        is_delete = request.POST["delete"]
        if is_delete == "はい":
            memo.delete()
        return HttpResponseRedirect(reverse("memos:memo-list"))
    return render(request, "memos/memo_confirm_delete.html", {"memo": memo})

memos/templates/memos/memo_confirm_delete.html
<!DOCTYPE html>
<html>
	<head>
		<title>My Memo App</title>
		{% load bootstrap5 %}
		{% bootstrap_css %}
		{% bootstrap_javascript %}
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&display=swap" rel="stylesheet">
	</head>
</html>

<div class="container">
	<form action="{% url "memos:memo-delete" memo.id %}" method="post" class="mt-4">
		{% csrf_token %}
		<p class="text-center">メモ「{{ memo.title }}」を削除しますか？</p>
		<div class="text-center">
			<input type="submit" name="delete" value="はい" class="btn btn-primary">
			<input type="submit" name="delete" value="いいえ" class="btn btn-light">
		</div>
	</form>
</div>

memos/templates/memos/memo_form.html
<!DOCTYPE html>
<html>
	<head>
		<title>My Memo App</title>
		{% load bootstrap5 %}
		{% bootstrap_css %}
		{% bootstrap_javascript %}
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&display=swap" rel="stylesheet">
	</head>
</html>

<div class="container">
	{% if memo %}
	<form action="{% url "memos:memo-edit" memo.id %}" method="post" class="mt-4">
		{% csrf_token %}
		{% if error_message %}
			<p>{{ error_message }}</p>
		{% endif %}
		<div class="mb-3">
			<label class="form-label">Title: </label>
			{{ form.title }}
		</div>
		<div class="mb-3">
			<label class="form-label">Content: </label>
			{{ form.content }}
		</div>
		<div class="mb-3">
			<label class="form-label">Created at: </label>
			{{ form.created_at }}
		</div>
		<div class="d-flex justify-content-between">
			<input type="submit" value="保存する" class="btn btn-primary">
			<a href="{% url "memos:memo-delete" memo.id %}" class="btn btn-light">メモを削除する</a>
		</div>
	</form>
	{% else %}
	<form action="{% url "memos:memo-create" %}" method="post" class="mt-4">
		{% csrf_token %}
		{% if error_message %}
			<p>{{ error_message }}</p>
		{% endif %}
		<div class="mb-3">
			<label class="form-label">Title: </label>
			{{ form.title }}
		</div>
		<div class="mb-3">
			<label class="form-label">Content: </label>
			{{ form.content }}
		</div>
		<div class="mb-3">
			<label class="form-label">Created at: </label>
			{{ form.created_at }}
		</div>
		<input type="submit" value="保存する" class="btn btn-primary">
	</form>
	{% endif %}
</div>

memos/templates/memos/memo_list.html
<!DOCTYPE html>
<html>
	<head>
		<title>My Memo App</title>
		{% load bootstrap5 %}
		{% bootstrap_css %}
		{% bootstrap_javascript %}
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&display=swap" rel="stylesheet">
	</head>
</html>

<div class="container">
	<div class="d-flex justify-content-between mt-4 mb-2">
		<h1>メモ一覧</h1>
		<p><a href="{% url "memos:memo-create" %}" class="btn btn-outline-primary">新しいメモを作成する</a></p>
	</div>
	<div class="list-group">
	{% for memo in memo_list %}
		<a href="{% url "memos:memo-edit" memo.id %}" class="list-group-item list-group-item-action">{{ memo.title }}</a>
	{% endfor %}
	</div>
</div>